layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
     - gajanan-choudhary

social_media:
  #website: https://users.oden.utexas.edu/~gajanan/
  linkedin: gajananchoudhary
  # hackerrank: your_username
  # stackoverflow: your_user_id
  facebook: gajananchoudhary91
  # instagram: your_username
  # youtube: your_username
  # behance: your_username
  # dribbble: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username

topics:
  - name: C/C++
    web_url: https://en.wikipedia.org/wiki/C++
    image_url: https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg

  - name: Python
    web_url: https://www.python.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg 

  - name: TensorFlow
    web_url: https://www.tensorflow.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg
